/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CantonControl;
import javax.swing.JInternalFrame;

/**
 *
 * @author Andres Ochoa
 */
public class ModificarCanton extends javax.swing.JInternalFrame {

    private CantonControl cantonControl= new CantonControl();
    /**
     * Creates new form ModificarCanton
     */
    public ModificarCanton() {
        initComponents();
        this.setClosable(true);
        this.setIconifiable(true);
        this.setResizable(true);
        this.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.actualizarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void actualizarTabla() {

        var data = new Object[this.cantonControl.listar().size()][7];
        for (var i = 0; i < this.cantonControl.listar().size(); i++) {

            data[i][0] = this.cantonControl.listar().get(i).getCodigo();
            data[i][1] = this.cantonControl.listar().get(i).getNombreCanton();
            data[i][2] = this.cantonControl.listar().get(i).getAreaTotalM2();
            data[i][3] = this.cantonControl.listar().get(i).getUpsActivas();
            data[i][4] = this.cantonControl.listar().get(i).getUniversidadesDisponibles();
            data[i][5] = this.cantonControl.listar().get(i).getNumeroHabitantes();
            data[i][6] = this.cantonControl.listar().get(i).getProvincia().getNumeroCiudades();
         

        }

        var encabezado = new String[7];
        encabezado[0] = "Codigo";
        encabezado[1] = "Canton";
        encabezado[2] = "Area Total";
        encabezado[3] = "UpsActivas";
        encabezado[4] = "UDisponibles";
        encabezado[5] = "NumHabitantes";
        encabezado[6] = "NumeroProvincia";
        
        
        

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, encabezado));

    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
